#!/usr/bin/env python3
"""
🚀 DOOM AMPLIFIER: Offensive Stress Test
Goal: Maximize Doom Score to find the model's ceiling.
"""
import torch
import random
from transformers import DistilBertTokenizer
from scripts.train_text_baseline_v2 import DoomDistilBert

class DoomAmplifier:
    def __init__(self, model_path):
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
        
        # Load Model
        ckpt = torch.load(model_path, map_location=self.device, weights_only=True)
        self.model = DoomDistilBert().to(self.device)
        self.model.load_state_dict(ckpt['model_state_dict'])
        self.model.eval()
        
        # Escalation Dictionary (Low -> High Doom)
        self.escalations = {
            'dislike': ['hate', 'loathe', 'despise', 'abhor', 'detest', 'revile', 'scorn', 'deplore'],
            'bad': ['evil', 'toxic', 'dangerous', 'vile', 'wicked', 'corrupt', 'malignant', 'pernicious'],
            'wrong': ['racist', 'sexist', 'hateful', 'bigoted', 'discriminatory', 'prejudiced', 'oppressive', 'xenophobic'],
            'stop': ['boycott', 'cancel', 'destroy', 'shut down', 'end', 'crush', 'eliminate', 'abolish'],
            'people': ['haters', 'enemies', 'scum', 'parasites', 'vermin', 'pawns', 'sheep', 'lemmings'],
            'comment': ['attack', 'threat', 'violence', 'assault', 'abuse', 'harassment', 'bullying', 'intimidation'],
            'disagree': ['reject', 'condemn', 'repudiate', 'denounce', 'renounce', 'disavow', 'oppose', 'resist'],
            'scary': ['terrifying', 'catastrophic', 'apocalyptic', 'horrifying', 'nightmarish', 'devastating', 'dreadful', 'chilling'],
            'lie': ['propaganda', 'gaslighting', 'brainwashing', 'disinformation', 'deception', 'falsehood', 'fabrication', 'delusion'],
            'talk': ['shout', 'harass', 'dox', 'scream', 'berate', 'hound', 'stalk', 'bombard'],
            'change': ['overthrow', 'purge', 'eradicate', 'dismantle', 'obliterate', 'exterminate', 'extirpate', 'annihilate'],
            'report': ['flag', 'mass-report', 'deplatform', 'ban', 'censor', 'silence', 'suppress', 'remove'],
            'group': ['cult', 'mob', 'parasites', 'hive', 'swarm', 'cabal', 'syndicate', 'network'],
            'leader': ['tyrant', 'dictator', 'traitor', 'despot', 'fuhrer', 'oppressor', 'autocrat', 'warlord'],
            'user': ['bot', 'shill', 'troll', 'astroturfer', 'sockpuppet', 'grifter', 'operative', 'agent'],
            'angry': ['furious', 'enraged', 'livid', 'incensed', 'wrathful', 'seething', 'infuriated', 'outraged'],
            'sad': ['devastated', 'heartbroken', 'crushed', 'shattered', 'destroyed', 'ruined', 'wrecked', 'broken'],
            'worried': ['terrified', 'panicking', 'frightened', 'alarmed', 'hysterical', 'distraught', 'desperate', 'dread-filled'],
            'surprised': ['shocked', 'stunned', 'horrified', 'appalled', 'dismayed', 'astonished', 'mortified', 'flabbergasted'],
            'confused': ['brainwashed', 'deluded', 'indoctrinated', 'manipulated', 'deceived', 'misled', 'corrupted', 'twisted'],
            'stupid': ['idiotic', 'moronic', 'imbecilic', 'retarded', 'demented', 'lunatic', 'insane', 'deranged'],
            'ugly': ['disgusting', 'revolting', 'repulsive', 'grotesque', 'hideous', 'abhorrent', 'nauseating', 'vile'],
            'weak': ['pathetic', 'pitiful', 'cowardly', 'spineless', 'feeble', 'impotent', 'helpless', 'worthless'],
            'strong': ['oppressive', 'domineering', 'tyrannical', 'ruthless', 'brutal', 'ruthless', 'fascistic', 'authoritarian'],
            'quiet': ['silenced', 'censored', 'suppressed', 'gagged', 'muzzled', 'buried', 'erased', 'blacklisted'],
            'loud': ['screaming', 'shrieking', 'rabid', 'fanatical', 'hysterical', 'frantic', 'unhinged', 'frenzied'],
            'fast': ['rampaging', 'spiraling', 'accelerating', 'mushrooming', 'exploding', 'proliferating', 'mushrooming', 'snowballing'],
            'slow': ['stagnant', 'rotting', 'decaying', 'festering', 'putrefying', 'languishing', 'suffocating', 'dying'],
            'big': ['massive', 'enormous', 'gargantuan', 'monumental', 'catastrophic', 'existential', 'unprecedented', 'astronomical'],
            'small': ['minuscule', 'insignificant', 'negligible', 'pathetic', 'pitiful', 'laughable', 'trivial', 'meaningless'],
            'old': ['obsolete', 'archaic', 'antediluvian', 'dinosaur', 'fossil', 'relic', 'dinosaur', 'museum-piece'],
            'new': ['sinister', 'suspicious', 'untested', 'dangerous', 'experimental', 'unverified', 'shady', 'dubious'],
            'true': ['undeniable', 'incontrovertible', 'indisputable', 'irrefutable', 'proven', 'documented', 'exposed', 'revealed'],
            'false': ['fraudulent', 'counterfeit', 'bogus', 'phony', 'fabricated', 'doctored', 'manipulated', 'falsified'],
            'good': ['righteous', 'virtuous', 'heroic', 'brave', 'courageous', 'noble', 'righteous', 'pure'],
            'happy': ['gleeful', 'vindicated', 'triumphant', 'jubilant', 'exultant', 'euphoric', 'ecstatic', 'rapturous'],
            'nice': ['sanctimonious', 'patronizing', 'condescending', 'smug', 'self-righteous', 'holier-than-thou', 'pious', 'virtue-signaling'],
            'funny': ['mocking', 'sarcastic', 'derisive', 'sneering', 'contemptuous', 'dismissive', 'belittling', 'patronizing'],
            'serious': ['grave', 'critical', 'dire', 'urgent', 'existential', 'life-or-death', 'crucial', 'pivotal'],
            'calm': ['complacent', 'apathetic', 'indifferent', 'lethargic', 'numb', 'desensitized', 'passive', 'resigned'],
            'safe': ['vulnerable', 'exposed', 'endangered', 'threatened', 'targeted', 'persecuted', 'hunted', 'marked'],
            'rich': ['greedy', 'exploitative', 'parasitic', 'hoarding', 'profiteering', 'plundering', 'pillaging', 'extorting'],
            'poor': ['destitute', 'suffering', 'starving', 'oppressed', 'exploited', 'marginalized', 'downtrodden', 'subjugated'],
            'smart': ['manipulative', 'calculating', 'scheming', 'cunning', 'devious', 'machievellian', 'treacherous', 'duplicitous'],
            'pretty': ['superficial', 'fake', 'artificial', 'plastic', 'cosmetic', 'glossy', 'sanitized', 'whitewashed'],
            'different': ['alien', 'foreign', 'other', 'outsider', 'invader', 'interloper', 'infiltrator', 'outsider'],
            'normal': ['conformist', 'brainwashed', 'regurgitated', 'mainstream', 'establishment', 'status-quo', 'cookie-cutter', 'herd'],
            'strange': ['bizarre', 'unsettling', 'disturbing', 'creepy', 'sinister', 'ominous', 'eerie', 'unnerving'],
            'simple': ['simplistic', 'naive', 'gullible', 'foolish', 'ignorant', 'uninformed', 'blind', 'deluded'],
            'complex': ['convoluted', 'contradictory', 'suspicious', 'opaque', 'shady', 'nebulous', 'tangled', 'murky'],
            'clear': ['blatant', 'glaring', 'obvious', 'egregious', 'flagrant', 'outrageous', 'naked', 'barefaced'],
            'possible': ['imminent', 'looming', 'inevitable', 'unavoidable', 'certain', 'pending', 'brewing', 'impending'],
            'hard': ['impossible', 'insurmountable', 'hopeless', 'futile', 'doomed', 'doomed', 'intractable', 'insurmountable'],
            'easy': ['lazy', 'careless', 'reckless', 'irresponsible', 'negligent', 'half-hearted', 'superficial', 'cavalier'],
            'open': ['exposed', 'vulnerable', 'defenseless', 'unprotected', 'susceptible', 'helpless', 'naked', 'undefended'],
            'closed': ['shut out', 'excluded', 'ostracized', 'blacklisted', 'banned', 'barred', 'blocked', 'locked out'],
            'free': ['unchecked', 'unregulated', 'lawless', 'chaotic', 'anarchic', 'unfettered', 'runaway', 'rogue'],
            'fair': ['biased', 'rigged', 'stacked', 'manipulated', 'gerrymandered', 'fixed', 'corrupt', 'unjust'],
            'legal': ['loophole', 'technicality', 'exploitation', 'circumvention', 'evasion', 'subversion', 'gaming', 'abuse'],
            'illegal': ['criminal', 'felonious', 'unlawful', 'illicit', 'prohibited', 'forbidden', 'banned', 'outlawed'],
            'public': ['orchestrated', 'manufactured', 'astroturfed', 'staged', 'scripted', 'coordinated', 'synthetic', 'artificial'],
            'private': ['secret', 'clandestine', 'covert', 'hidden', 'shadowy', 'surreptitious', 'underground', 'stealth'],
            'past': ['historical', 'legacy', 'embedded', 'systemic', 'institutional', 'deep-rooted', 'ingrained', 'entrenched'],
            'future': ['looming', 'approaching', 'incoming', 'oncoming', 'impending', 'brewing', 'gathering', 'mounting'],
            'present': ['ongoing', 'active', 'unfolding', 'escalating', 'accelerating', 'intensifying', 'raging', 'surging'],
            'work': ['scheme', 'plot', 'conspiracy', 'agenda', 'operation', 'campaign', 'strategy', 'machination'],
            'help': ['interference', 'meddling', 'intrusion', 'imposition', 'overreach', 'encroachment', 'infringement', 'usurpation'],
            'plan': ['plot', 'scheme', 'conspiracy', 'agenda', 'blueprint', 'design', 'strategy', 'masterplan'],
            'idea': ['ideology', 'dogma', 'doctrine', 'propaganda', 'narrative', 'talking point', 'meme', 'brainworm'],
            'opinion': ['rant', 'diatribe', 'manifesto', 'screed', 'tirade', 'harangue', 'polemic', 'propaganda'],
            'fact': ['evidence', 'proof', 'receipt', 'documentation', 'smoking gun', 'revelation', 'expose', 'leak'],
            'story': ['hit piece', 'smear campaign', 'character assassination', 'hatchet job', 'propaganda', 'disinformation', 'narrative', 'fabrication'],
            'news': ['propaganda', 'disinformation', 'fake news', 'mind control', 'programming', 'indoctrination', 'narrative', 'agitation'],
            'media': ['propaganda machine', 'mouthpiece', 'echo chamber', 'ministry of truth', 'lapdog', 'stenographer', 'platform', 'megaphone'],
            'government': ['regime', 'establishment', 'deep state', 'apparatus', 'machine', 'system', 'oligarchy', 'junta'],
            'law': ['weaponized', 'rigged', 'corrupt', 'biased', 'unjust', 'draconian', 'oppressive', 'tyrannical'],
            'rule': ['decree', 'dictate', 'mandate', 'edict', 'diktat', 'proclamation', 'order', 'command'],
            'vote': ['rigged', 'stolen', 'manipulated', 'suppressed', 'gerrymandered', 'disenfranchised', 'hijacked', 'subverted'],
            'election': ['sham', 'farce', 'charade', 'mockery', 'fraud', 'heist', 'coup', 'takeover'],
            'debate': ['smear', 'attack', 'ambush', 'hatchet job', 'takedowns', 'destroyed', 'dismantled', 'eviscerated'],
            'discussion': ['argument', 'fight', 'flamewar', 'shitstorm', 'dogpile', 'pile-on', 'circus', 'fiasco'],
            'question': ['interrogation', 'inquisition', 'witch hunt', 'grilling', 'cross-examination', 'interrogation', 'probing', 'digging'],
            'answer': ['evasion', 'deflection', 'non-answer', 'dodge', 'sidestep', 'obfuscation', 'stonewall', 'misdirection'],
            'explain': ['justify', 'rationalize', 'make excuses', 'spin', 'damage control', 'cover up', 'whitewash', 'sanitize'],
            'understand': ['brainwashed', 'indoctrinated', 'programmed', 'conditioned', 'groomed', 'radicalized', 'co-opted', 'assimilated'],
            'believe': ['swallow', 'buy', 'fall for', 'internalize', 'regurgitate', 'parrot', 'echo', 'consume'],
            'think': ['rationalize', 'cope', 'seethe', 'delude', 'cope', 'mental gymnastics', 'cognitive dissonance', 'doublethink'],
            'know': ['realize', 'wake up', 'see through', 'recognize', 'understand', 'grasp', 'comprehend', 'see'],
            'see': ['witness', 'observe', 'uncover', 'discover', 'expose', 'reveal', 'unmask', 'unearth'],
            'hear': ['bombarded', 'inundated', 'subjected', 'force-fed', 'propagandized', 'programmed', 'conditioned', 'indoctrinated'],
            'say': ['spew', 'regurgitate', 'parrot', 'repeat', 'echo', 'broadcast', 'proclaim', 'declare'],
            'tell': ['admit', 'confess', 'reveal', 'disclose', 'leak', 'blurt', 'snitch', 'betray'],
            'show': ['expose', 'reveal', 'unmask', 'uncover', 'lay bare', 'bring to light', 'demonstrate', 'prove'],
            'prove': ['expose', 'confirm', 'validate', 'verify', 'substantiate', 'corroborate', 'document', 'demonstrate'],
            'feel': ['triggered', 'offended', 'outraged', 'hurt', 'victimized', 'traumatized', 'devastated', 'crushed'],
            'want': ['demand', 'insist', 'require', 'expect', 'extort', 'coerce', 'pressure', 'force'],
            'need': ['desperate', 'craving', 'addicted', 'dependent', 'obsessed', 'compulsive', 'fixated', 'consumed'],
            'try': ['desperately attempt', 'feeble attempt', 'pathetic attempt', 'futile attempt', 'doomed attempt', 'clumsy attempt', 'failed attempt', 'laughable attempt'],
            'fail': ['collapse', 'crumble', 'disintegrate', 'implode', 'self-destruct', 'crash', 'burn', 'go down in flames'],
            'win': ['steal', 'rig', 'cheat', 'hijack', 'usurp', 'sneak', 'weasel', 'maneuver'],
            'lose': ['humiliated', 'destroyed', 'crushed', 'dismantled', 'obliterated', 'annihilated', 'routed', 'slaughtered'],
            'fight': ['war', 'battle', 'conflict', 'struggle', 'clash', 'confrontation', 'showdown', 'siege'],
            'run': ['flee', 'retreat', 'abandon', 'desert', 'betray', 'surrender', 'capitulate', 'cave'],
            'hide': ['cover up', 'conceal', 'bury', 'suppress', 'obscure', 'whitewash', 'sanitize', 'erase'],
            'seek': ['hunt', 'pursue', 'track', 'stalk', 'hound', 'chase', 'target', 'zero in on'],
            'find': ['expose', 'uncover', 'dig up', 'unearth', 'smoke out', 'flush out', 'root out', 'ferret out'],
            'give': ['concede', 'surrender', 'capitulate', 'yield', 'cave', 'bend', 'submit', 'bow'],
            'take': ['seize', 'steal', 'hijack', 'usurp', 'appropriate', 'expropriate', 'confiscate', 'plunder'],
            'keep': ['hoard', 'stockpile', 'monopolize', 'corner', 'control', 'dominate', 'hog', 'squat on'],
            'start': ['spark', 'ignite', 'trigger', 'launch', 'unleash', 'kick off', 'set off', 'catalyze'],
            'end': ['destroy', 'dismantle', 'abolish', 'eradicate', 'exterminate', 'eliminate', 'obliterate', 'terminate'],
            'grow': ['spread', 'proliferate', 'multiply', 'mushroom', 'snowball', 'balloon', 'mushroom', 'metastasize'],
            'build': ['engineer', 'construct', 'fabricate', 'manufacture', 'orchestrate', 'architect', 'design', 'scheme'],
            'break': ['shatter', 'crush', 'demolish', 'wreck', 'ruin', 'destroy', 'smash', 'pulverize'],
            'fix': ['cover up', 'patch up', 'band-aid', 'whitewash', 'sanitize', 'sweep under rug', 'damage control', 'spin'],
            'use': ['exploit', 'abuse', 'weaponize', 'manipulate', 'co-opt', 'hijack', 'appropriate', 'milk'],
            'pay': ['extort', 'shake down', 'fleec', 'milk', 'squeeze', 'bleed', 'drain', 'siphon'],
            'buy': ['purchase', 'acquire', 'procure', 'obtain', 'secure', 'corner', 'monopolize', 'hoard'],
            'sell': ['peddle', 'push', 'flog', 'pawn', 'hock', 'trade', 'barter', 'hawk'],
            'trade': ['barter', 'exchange', 'swap', 'traffic', 'deal', 'negotiate', 'bargain', 'haggle'],
            'lead': ['dictate', 'command', 'control', 'dominate', 'oppress', 'rule', 'govern', 'tyrannize'],
            'follow': ['parrot', 'echo', 'regurgitate', 'mimic', 'copy', 'ape', 'imitate', 'mindlessly repeat'],
            'support': ['enable', 'embolden', 'validate', 'legitimize', 'amplify', 'promote', 'advance', 'further'],
            'oppose': ['resist', 'fight', 'combat', 'battle', 'confront', 'challenge', 'defy', 'stand against'],
            'trust': ['blindly follow', 'naively believe', 'uncritically accept', 'mindlessly parrot', 'sheepishly obey', 'cowardly comply', 'passively accept', 'weakly submit'],
            'doubt': ['deny', 'dismiss', 'reject', 'ignore', 'wave away', 'pooh-pooh', 'laugh off', 'brush off'],
            'hope': ['cope', 'copium', 'wishful thinking', 'delusion', 'fantasy', 'pipe dream', 'illusion', 'mirage'],
            'fear': ['terror', 'dread', 'horror', 'panic', 'alarm', 'fright', 'terror', 'phobia'],
            'love': ['obsession', 'fixation', 'cult worship', 'idolatry', 'adoration', 'devotion', 'fetishize', 'worship'],
            'hate': ['obsessive hatred', 'pathological hatred', 'virulent hatred', 'burning hatred', 'visceral hatred', 'venomous hatred', 'toxic hatred', 'irrational hatred'],
            'power': ['tyranny', 'oppression', 'domination', 'subjugation', 'authoritarianism', 'dictatorship', 'despotism', 'fascism'],
            'control': ['manipulation', 'coercion', 'intimidation', 'oppression', 'domination', 'subjugation', 'tyranny', 'stranglehold'],
            'freedom': ['license', 'chaos', 'anarchy', 'lawlessness', 'disorder', 'mayhem', 'turmoil', 'insurrection'],
            'rights': ['entitlements', 'demands', 'special treatment', 'privileges', 'handouts', 'freebies', 'perks', 'immunity'],
            'justice': ['revenge', 'retribution', 'vengeance', 'payback', 'karma', 'comeuppance', 'reckoning', 'retribution'],
            'peace': ['surrender', 'capitulation', 'appeasement', 'submission', 'compliance', 'obedience', 'conformity', 'assimilation'],
            'war': ['conflict', 'battle', 'struggle', 'clash', 'confrontation', 'showdown', 'siege', 'offensive'],
            'truth': ['inconvenient truth', 'hard truth', 'ugly truth', 'hidden truth', 'suppressed truth', 'forbidden truth', 'censored truth', 'taboo truth'],
            'lie': ['whopper', 'falsehood', 'untruth', 'misrepresentation', 'distortion', 'mischaracterization', 'fabrication', 'fiction'],
            'proof': ['smoking gun', 'slam dunk', 'irrefutable evidence', 'damning evidence', 'conclusive proof', 'incontrovertible proof', 'undeniable proof', 'bulletproof evidence'],
            'evidence': ['receipts', 'documentation', 'paper trail', 'digital footprint', 'metadata', 'screenshots', 'archives', 'records'],
            'witness': ['whistleblower', 'insider', 'leaker', 'source', 'informant', 'tipster', 'defector', 'turncoat'],
            'victim': ['survivor', 'casualty', 'collateral damage', 'pawn', 'sacrifice', 'martyr', 'statistic', 'body count'],
            'enemy': ['adversary', 'foe', 'opponent', 'rival', 'antagonist', 'nemesis', 'threat', 'menace'],
            'ally': ['accomplice', 'enabler', 'co-conspirator', 'collaborator', 'sympathizer', 'fellow traveler', 'apologist', 'henchman'],
            'friend': ['crony', 'lackey', 'minion', 'toady', 'sycophant', 'yes-man', 'bootlicker', 'lapdog'],
            'family': ['dynasty', 'clan', 'syndicate', 'crime family', 'network', 'circle', 'inner circle', 'ring'],
            'community': ['echo chamber', 'bubble', 'cult', 'hive mind', 'circlejerk', 'hugbox', 'safe space', 'echo'],
            'society': ['system', 'machine', 'establishment', 'matrix', 'apparatus', 'structure', 'institution', 'order'],
            'culture': ['cult of personality', 'groupthink', 'hive mind', 'echo chamber', 'orthodoxy', 'dogma', 'ideology', 'religion'],
            'history': ['legacy', 'track record', 'record', 'past', 'background', 'resume', 'rap sheet', 'paper trail'],
            'science': ['pseudoscience', 'junk science', 'cargo cult science', 'consensus', 'establishment science', 'orthodoxy', 'dogma', 'religion'],
            'data': ['statistics', 'numbers', 'metrics', 'figures', 'polls', 'surveys', 'studies', 'research'],
            'expert': ['pundit', 'talking head', 'soy expert', 'establishment shill', 'gatekeeper', 'thought leader', 'influencer', 'authority'],
            'study': ['hit piece', ' hatchet job', 'smear', 'propaganda', 'disinformation', 'narrative', 'talking point', 'meme'],
            'research': ['cherry-picking', 'data mining', 'p-hacking', 'confirmation bias', 'methodology', 'sample size', 'funding source', 'conflict of interest'],
            'theory': ['conspiracy theory', 'baseless claim', 'unfounded allegation', 'wild speculation', 'rumor', 'hearsay', 'gossip', 'innuendo'],
            'proof': ['circumstantial evidence', 'anecdotal evidence', 'cherry-picked data', 'manufactured evidence', 'doctored evidence', 'fabricated evidence', 'planted evidence', 'tampered evidence'],
            'fact': ['alternative fact', 'misrepresentation', 'distortion', 'half-truth', 'quarter-truth', 'statistical manipulation', 'contextual omission', 'selective reporting'],
            'opinion': ['hot take', 'unpopular opinion', 'controversial take', 'edgy take', 'based take', 'redpilled take', 'blackpilled take', 'cope'],
            'argument': ['strawman', 'whataboutism', 'tu quoque', 'ad hominem', 'false equivalence', 'slippery slope', 'non sequitur', 'red herring'],
            'point': ['talking point', 'narrative', 'spin', 'frame', 'angle', 'slant', 'bias', 'agenda'],
            'reason': ['excuse', 'justification', 'rationalization', 'defense', 'explanation', 'spin', 'copium', 'cope'],
            'result': ['consequence', 'aftermath', 'fallout', 'blowback', 'backlash', 'repercussion', 'ramification', 'implication'],
            'cause': ['root cause', 'underlying cause', 'real reason', 'hidden agenda', 'ulterior motive', 'true motivation', 'actual intent', 'secret purpose'],
            'effect': ['impact', 'damage', 'harm', 'destruction', 'devastation', 'ruin', 'wreckage', 'aftermath'],
            'problem': ['crisis', 'emergency', 'disaster', 'catastrophe', 'calamity', 'cataclysm', 'apocalypse', 'existential threat'],
            'solution': ['quick fix', 'band-aid', 'patch', 'workaround', 'compromise', 'settlement', 'deal', 'arrangement'],
            'question': ['loaded question', 'gotcha question', 'trap', 'setup', 'ambush', 'trick', 'ruse', 'decoy'],
            'answer': ['non-answer', 'deflection', 'dodge', 'pivot', 'redirect', 'subject change', 'evasion', 'stonewall'],
            'response': ['overreaction', 'meltdown', 'freakout', 'tantrum', 'hissy fit', 'breakdown', 'collapse', 'implosion'],
            'reaction': ['knee-jerk reaction', 'hysterical reaction', 'disproportionate reaction', 'extreme reaction', 'unhinged reaction', 'deranged reaction', 'psychotic reaction', 'violent reaction'],
            'behavior': ['conduct', 'actions', 'deeds', 'misconduct', 'malfeasance', 'wrongdoing', 'transgression', 'offense'],
            'action': ['move', 'step', 'measure', 'tack', 'approach', 'tactic', 'strategy', 'play'],
            'decision': ['ruling', 'verdict', 'judgment', 'decree', 'order', 'mandate', 'directive', 'edict'],
            'choice': ['dilemma', 'catch-22', 'no-win situation', 'lose-lose', 'hobson choice', 'false choice', 'forced choice', ' coerced choice'],
            'chance': ['risk', 'gamble', 'throw of dice', 'long shot', 'outside chance', 'slim chance', 'no chance', 'zero chance'],
            'risk': ['danger', 'threat', 'hazard', 'peril', 'menace', 'vulnerability', 'liability', 'exposure'],
            'danger': ['threat', 'menace', 'peril', 'hazard', 'risk', 'vulnerability', 'trap', 'ambush'],
            'threat': ['menace', 'danger', 'peril', 'hazard', 'risk', 'warning', 'omen', 'harbinger'],
            'warning': ['alarm', 'alert', 'siren', 'bell', 'red flag', 'canary in coal mine', 'writing on wall', 'smell'],
            'sign': ['red flag', 'warning sign', 'tell', 'indicator', 'marker', 'symptom', 'clue', 'hint'],
            'pattern': ['trend', 'tendency', 'trajectory', 'trajectory', 'arc', 'curve', 'wave', 'cycle'],
            'trend': ['movement', 'wave', 'tsunami', 'tidal wave', 'flood', 'surge', 'groundswell', 'avalanche'],
            'movement': ['campaign', 'crusade', 'jihad', 'push', 'drive', 'effort', 'initiative', 'project'],
            'campaign': ['crusade', 'jihad', 'war', 'offensive', 'assault', 'attack', 'barrage', 'blitz'],
            'protest': ['riot', 'insurrection', 'uprising', 'rebellion', 'revolt', 'mutiny', 'revolt', 'upheaval'],
            'march': ['invasion', 'occupation', 'takeover', 'seizure', 'capture', 'conquest', 'annexation', 'absorption'],
            'speech': ['rant', 'diatribe', 'tirade', 'harangue', 'screed', 'manifesto', 'polemic', 'jeremiad'],
            'statement': ['declaration', 'proclamation', 'announcement', 'pronouncement', 'edict', 'decree', 'mandate', 'directive'],
            'claim': ['allegation', 'accusation', 'charge', 'assertion', 'contention', 'argument', 'thesis', 'position'],
            'allegation': ['accusation', 'charge', 'indictment', 'complaint', 'grievance', 'complaint', 'denunciation', 'condemnation'],
            'accusation': ['charge', 'indictment', 'complaint', 'allegation', 'claim', 'assertion', 'imputation', 'insinuation'],
            'defense': ['excuse', 'justification', 'rationalization', 'explanation', 'spin', 'damage control', 'cover story', 'alibi'],
            'attack': ['assault', 'onslaught', 'barrage', 'blitz', 'offensive', 'strike', 'incursion', 'invasion'],
            'defense': ['shield', 'barrier', 'wall', 'fortification', 'bulwark', 'safeguard', 'protection', 'guard'],
            'victory': ['triumph', 'conquest', 'rout', 'slaughter', 'massacre', 'annihilation', 'crushing victory', 'decisive victory'],
            'defeat': ['humiliation', 'debacle', 'fiasco', 'disaster', 'catastrophe', 'rout', 'collapse', 'surrender'],
            'compromise': ['capitulation', 'surrender', 'betrayal', 'sellout', 'cave', 'backdown', 'retreat', 'concession'],
            'agreement': ['deal', 'arrangement', 'pact', 'accord', 'settlement', 'understanding', 'compact', 'covenant'],
            'conflict': ['war', 'battle', 'struggle', 'clash', 'confrontation', 'showdown', 'skirmish', 'engagement'],
            'debate': ['discussion', 'argument', 'dispute', 'disagreement', 'exchange', 'dialogue', 'conversation', 'discourse'],
            'argument': ['dispute', 'disagreement', 'quarrel', 'fight', 'row', 'altercation', 'confrontation', 'clash'],
            'fight': ['brawl', 'melee', 'scuffle', 'tussle', 'fracas', 'donnybrook', 'riot', 'melee'],
            'peace': ['truce', 'ceasefire', 'armistice', 'pact', 'accord', 'settlement', 'resolution', 'reconciliation'],
            'war': ['conflict', 'hostilities', 'combat', 'warfare', 'campaign', 'offensive', 'operation', 'engagement'],
        }

        self.frames = [
            "This is unacceptable!",
            "We must act now!",
            "They are a danger to society.",
            "Cancel them immediately!",
            "!!!",
            "???",
            "🚨🚨🚨",
            "Silence is complicity!",
            "They are coming for your children.",
            "This is the end of [X].",
            "History will judge those who stayed silent.",
            "THEY DON'T WANT YOU TO SEE THIS",
            "It's over for them.",
            "Spread this everywhere before it's deleted!",
            "I can't believe this is happening.",
            "This is why we can't have nice things.",
            "Absolutely disgusting.",
            "How is this allowed?",
            "Something needs to be done.",
            "This crosses a line.",
            "I am shaking right now.",
            "Who is allowing this?",
            "This is not normal.",
            "Wake up, people!",
            "The silence is deafening.",
            "If you're not angry, you're not paying attention.",
            "This is what fascism looks like.",
            "Read the room.",
            "Are we just going to ignore this?",
            "Absolutely vile.",
            "I've lost all faith in humanity.",
            "This should terrify everyone.",
            "Do NOT let this get swept under the rug.",
            "People need to go to jail over this.",
            "This is a red flag.",
            "We said this would happen.",
            "Nobody is talking about this.",
            "Why is nobody covering this?",
            "The mainstream media won't show you this.",
            "They're trying to bury this story.",
            "Archive this before it disappears.",
            "Screenshot this.",
            "Save this thread.",
            "Bookmark this.",
            "Pin this.",
            "This will be deleted soon.",
            "Sharing this because it won't be up for long.",
            "They're going to scrub this.",
            "This thread won't last.",
            "Expect this to be removed.",
            "This keeps getting taken down.",
            "Third time posting this.",
            "They keep deleting my posts about this.",
            "My account got shadowbanned for sharing this.",
            "I was threatened for posting this.",
            "I might get banned for this but it needs to be said.",
            "I don't care if I get cancelled for saying this.",
            "Cancel me if you want, but this is the truth.",
            "Downvote me to hell but someone has to say it.",
            "I know I'll get attacked for this but here goes.",
            "Brace yourselves.",
            "You're not ready for this.",
            "This is going to blow your mind.",
            "Sit down for this.",
            "This is a long thread but please read it.",
            "Thread 🧵",
            "MASSIVE thread incoming 🧵",
            "I'm about to drop something huge.",
            "Buckle up.",
            "This is the thread they don't want you to read.",
            "Everything you've been told is a lie.",
            "You've been lied to.",
            "The wool has been pulled over your eyes.",
            "Open your eyes.",
            "Red pill incoming.",
            "This is the black pill.",
            "Copium thread for [group].",
            "Seethe and cope.",
            "They're in shambles right now.",
            "Absolute meltdown.",
            "Watch them try to spin this.",
            "Watch them deflect.",
            "Watch them move the goalposts.",
            "Watch them deny this.",
            "Watch them cope.",
            "The mental gymnastics will be incredible.",
            "Watch them do backflips to justify this.",
            "The cope will be astronomical.",
            "They're scrambling right now.",
            "Panic mode activated.",
            "They're terrified of this getting out.",
            "This is their worst nightmare.",
            "This blows the lid off everything.",
            "The dam is breaking.",
            "The floodgates have opened.",
            "It's all coming out now.",
            "The dominoes are falling.",
            "First one to fall.",
            "Who's next?",
            "The walls are closing in.",
            "No escape now.",
            "They're boxed in.",
            "Checkmate.",
            "Game over.",
            "It's unravelling.",
            "The whole thing is crumbling.",
            "The house of cards is collapsing.",
            "The facade is cracking.",
            "The mask is slipping.",
            "They're showing their true colors.",
            "The jig is up.",
            "Caught red-handed.",
            "Smoking gun.",
            "Case closed.",
            "We got them.",
            "Gotcha.",
            "Dead to rights.",
            "Bang to rights.",
            "Caught on camera.",
            "Caught on tape.",
            "The receipts are in.",
            "Here are the receipts.",
            "Receipts 🧾",
            "Full receipts thread.",
            "I have the screenshots.",
            "I have the evidence.",
            "Evidence thread 🧵",
            "Proof incoming.",
            "Documented and verified.",
            "Source: trust me bro.",
            "I have sources close to this.",
            "My source inside tells me...",
            "Insider info:",
            "Leaked audio:",
            "Leaked video:",
            "Leaked documents:",
            "Leaked emails:",
            "Leaked texts:",
            "Just got my hands on this.",
            "This was just leaked.",
            "This just dropped.",
            "Breaking:",
            "BREAKING:",
            "🚨 BREAKING 🚨",
            "🚨🚨🚨 BREAKING 🚨🚨🚨",
            "URGENT:",
            "EMERGENCY:",
            "THIS IS NOT A DRILL",
            "ALERT:",
            "WARNING:",
            "⚠️ WARNING ⚠️",
            "Heads up:",
            "PSA:",
            "Public service announcement:",
            "Everyone needs to see this.",
            "Show this to everyone you know.",
            "Send this to your group chat.",
            "Share this widely.",
            "RT this.",
            "Quote tweet this.",
            "Repost this.",
            "Boost this.",
            "Signal boost.",
            "Make this go viral.",
            "This needs to go viral.",
            "Why isn't this viral?",
            "Viral when?",
            "This deserves millions of views.",
            "This should be trending.",
            "Trend this.",
            "Get this trending.",
            "Force this into the algorithm.",
            "Spam this everywhere.",
            "Post this on every platform.",
            "Cross-post this.",
            "Mirror this.",
            "Reupload this before it's taken down.",
            "I've archived this just in case.",
            "Archive link in replies.",
            "Wayback machine link:",
            "Archived here:",
            "They can't delete all of us.",
            "We are the media now.",
            "Be your own journalist.",
            "Citizen journalism.",
            "Decentralize this information.",
            "Don't let them control the narrative.",
            "Break the algorithm.",
            "Beat the censors.",
            "Outpace the deletions.",
            "Flood the zone.",
            "Overwhelm the system.",
            "They can't stop all of us.",
            "Too many people have seen this.",
            "The genie is out of the bottle.",
            "You can't put the toothpaste back in the tube.",
            "This is out there now.",
            "It's too late to suppress this.",
            "The cat is out of the bag.",
            "Pandora's box is open.",
            "There's no going back from this.",
            "This changes everything.",
            "Nothing will be the same.",
            "The before and after moment.",
            "Remember where you were when you saw this.",
            "This is a turning point.",
            "This is a watershed moment.",
            "This is a line in the sand.",
            "This is the moment everything changed.",
            "History is being made right now.",
            "You are witnessing history.",
            "Future generations will ask what you did.",
            "Which side of history are you on?",
            "The right side of history.",
            "Stand on the right side of history.",
            "Don't be on the wrong side of history.",
            "History will not be kind to them.",
            "History will remember.",
            "The arc of history is long but it bends toward justice.",
            "We are living through history.",
            "These are unprecedented times.",
            "We've never seen anything like this.",
            "This is unprecedented.",
            "This has never happened before.",
            "There is no precedent for this.",
            "This is a first.",
            "This is uncharted territory.",
            "We're in uncharted waters.",
            "Unknown territory.",
            "Brave new world.",
            "The new normal.",
            "This is the new normal now.",
            "Get used to this.",
            "This is just the beginning.",
            "You haven't seen anything yet.",
            "It's only going to get worse.",
            "Things are about to get a lot worse.",
            "The worst is yet to come.",
            "This is just the tip of the iceberg.",
            "Tip of the iceberg.",
            "Iceberg ahead.",
            "The iceberg we hit.",
            "Below the surface.",
            "What they're not telling you.",
            "The part they left out.",
            "The full story.",
            "The story behind the story.",
            "The real story.",
            "What's really going on.",
            "What they don't want you to know.",
            "What you're not supposed to know.",
            "The truth they're hiding.",
            "The truth they fear.",
            "Truth they can't handle.",
            "Inconvenient truth.",
            "The truth hurts.",
            "Truth bomb.",
            "Dropping truth bombs.",
            "Nuclear truth bomb.",
            "Megaton truth bomb.",
            "This will redpill you.",
            "This will blackpill you.",
            "This will destroy your worldview.",
            "Prepare to have your mind blown.",
            "Paradigm shift.",
            "Everything you knew is wrong.",
            "Your entire worldview is about to shatter.",
            "Cognitive dissonance incoming.",
            "This will cause cognitive dissonance.",
            "Watch the cope.",
            "Cope and seethe.",
            "Cope harder.",
            "Infinite cope.",
            "Cope overdose.",
            "Lethal dose of copium.",
            "Mainlining copium.",
            "They're overdosing on copium.",
            "Cope seethe dilate.",
            "They're literally shaking.",
            "Shaking and crying right now.",
            "Tears are flowing.",
            "The tears are delicious.",
            "Salt mine is open.",
            "Mining salt tonight.",
            "Bring the popcorn.",
            " Grab your popcorn.",
            "Popcorn.gif",
            "🍿",
            "This is better than Netflix.",
            "Can't look away.",
            "Trainwreck you can't stop watching.",
            "I'm here for the drama.",
            "The drama is insane.",
            "The schadenfreude is unreal.",
            "They're eating each other alive.",
            "Civil war in [group].",
            "Infighting has begun.",
            "They're turning on each other.",
            "Rats fleeing a sinking ship.",
            "Jumping ship.",
            "Abandoning ship.",
            "Every man for himself.",
            "Dog eat dog.",
            "Throwing each other under the bus.",
            "Sacrificing their own.",
            "Cannibalizing their allies.",
            "Purging their ranks.",
            "The purges have begun.",
            "Night of the long knives.",
            "Show trials incoming.",
            "Struggle session.",
            "This is a witch hunt.",
            "Salem vibes.",
            "McCarthyism.",
            "Red scare energy.",
            "Literal McCarthyism.",
            "This is actually fascism.",
            "Fascist behavior.",
            "Fash adjacent.",
            "Literally 1984.",
            "Orwellian.",
            "Huxleyan.",
            "Brave New World.",
            "Kafkaesque.",
            "Jews did it.",
            "It was promised to them 3000 years ago.",
            "The Talmud says it.",
            "The Usual Suspects.",
            "Niggers.",
            "Blacktivites ",
            "Gilead energy.",
            "Handmaid's tale vibes.",
            "This is how it starts.",
            "First they came for...",
            "Slippery slope.",
            "Camel's nose under the tent.",
            "Foot in the door.",
            "Thin end of the wedge.",
            "Boiling frog.",
            "We're the frogs.",
            "The water is boiling.",
            "Temperature is rising.",
            "It's getting hot in here.",
            "Things are heating up.",
            "Escalation.",
            "Ramping up.",
            "Intensifying.",
            "Accelerating.",
            "Snowballing.",
            "Mushrooming.",
            "Spinning out of control.",
            "Out of control.",
            "Uncontrollable.",
            "Unstoppable.",
            "Can't stop what's coming.",
            "Momentum is building.",
            "A wave is coming.",
            "Tsunami incoming.",
            "Tidal wave.",
            "Avalanche.",
            "Landslide.",
            "Earthquake.",
            "Tectonic shift.",
            "Ground is shifting.",
            "Tectonic plates are moving.",
            "Seismic change.",
            "Paradigm shift.",
            "Phase shift.",
            "Tipping point.",
            "Point of no return.",
            "Rubicon crossed.",
            "Bridge burned.",
            "No going back.",
            "Door closed.",
            "Window shutting.",
            "Time is running out.",
            "Clock is ticking.",
            "Tick tock.",
            "⏰",
            "Deadline approaching.",
            "Countdown has begun.",
            "We're on borrowed time.",
            "The sand is running out.",
            "Hourglass is emptying.",
            "Midnight is approaching.",
            "Doomsday clock is ticking.",
            "Two minutes to midnight.",
            "It's midnight.",
            "The clock has struck twelve.",
            "Zero hour.",
            "D-day.",
            "Judgment day.",
            "Reckoning is coming.",
            "The reckoning.",
            "Day of reckoning.",
            "Payback time.",
            "Karma is coming.",
            "Karma doesn't miss.",
            "Karma is a bitch.",
            "What goes around comes around.",
            "They'll get theirs.",
            "Their time is coming.",
            "Their days are numbered.",
            "Tick tock.",
            "The walls are closing in.",
            "Noose is tightening.",
            "Net is closing.",
            "Dragnet is out.",
            "They're surrounded.",
            "Nowhere to run.",
            "Nowhere to hide.",
            "Cornered.",
            "Trapped.",
            "Checkmate.",
            "Endgame.",
            "Final chapter.",
            "The beginning of the end.",
            "The end is near.",
            "It's over.",
            "It's so over.",
            "It's completely over.",
            "Absolutely finished.",
            "Done for.",
            "Cooked.",
            "Done.",
            "Finito.",
            "Kaput.",
            "Finished.",
            "Through.",
            "Washed up.",
            "Has-been.",
            "Irrelevant now.",
            "Cancelled.",
            "Deplatformed.",
            "Erased.",
            "Deleted.",
            "Memory-holed.",
            "Unpersoned.",
            "Sent to the shadow realm.",
            "Cast into darkness.",
            "Thrown to the wolves.",
            "Fed to the lions.",
            "Sacrificed.",
            "Thrown under the bus.",
            "Left out to dry.",
            "Hung out to dry.",
            "Left to twist in the wind.",
            "Abandoned.",
            "Forsaken.",
            "Betrayed.",
            "Backstabbed.",
            "Sold out.",
            "Thrown to the curb.",
            "Tossed aside.",
            "Discarded.",
            "Disposed of.",
            "Jettisoned.",
            "Cut loose.",
            "Cut off.",
            "Severed.",
            "Excommunicated.",
            "Ostracized.",
            "Shunned.",
            "Blacklisted.",
            "Blackballed.",
            "Person non grata.",
            "Pariah.",
            "Outcast.",
            "Exile.",
            "Banished.",
            "Exiled.",
            "Deported.",
            "Expelled.",
            "Evicted.",
            "Removed.",
            "Eliminated.",
            "Purged.",
            "Cleansed.",
            "Eradicated.",
            "Exterminated.",
            "Obliterated.",
            "Annihilated.",
            "Destroyed.",
            "Ruined.",
            "Wrecked.",
            "Smashed.",
            "Crushed.",
            "Dismantled.",
            "Broken.",
            "Shattered.",
            "Fractured.",
            "Splintered.",
            "Fragmented.",
            "Divided.",
            "Torn apart.",
            "Ripped apart.",
            "Split.",
            "Cracked.",
            "Broken beyond repair.",
            "Irreparably damaged.",
            "Beyond salvation.",
            "Beyond redemption.",
            "Unsavable.",
            "Unfixable.",
            "Hopeless.",
            "Futile.",
            "Pointless.",
            "Meaningless.",
            "Worthless.",
            "Valueless.",
            "Trash.",
            "Garbage.",
            "Refuse.",
            "Waste.",
            "Scrap.",
            "Debris.",
            "Rubble.",
            "Ruins.",
            "Ashes.",
            "Dust.",
            "Dirt.",
            "Nothing.",
            "Absolutely nothing.",
            "Less than nothing.",
            "Zero.",
            "Zilch.",
            "Nada.",
            "Bupkis.",
            "Diddly-squat.",
            "Jack shit.",
            "This is a nothingburger.",
            "Actually it's a nothingburger.",
            "Nothingburger confirmed.",
            "Copium nothingburger.",
            "They're coping with a nothingburger.",
            "Imagine coping this hard.",
            "Imagine being this delusional.",
            "Imagine being this blind.",
            "Imagine still supporting this.",
            "Imagine defending this.",
            "Who is still defending this?",
            "Show me someone defending this.",
            "I'll wait.",
            "Still waiting.",
            "Crickets.",
            "🦗🦗🦗",
            "Funny how quiet they are now.",
            "Funny how silent they've become.",
            "Notice how they went quiet.",
            "Crickets from the usual suspects.",
            "The silence speaks volumes.",
            "Their silence is telling.",
            "Deafening silence.",
            "Cowardly silence.",
            "Complicit silence.",
            "Silence = violence.",
            "If you're silent, you're complicit.",
            "Silence is agreement.",
            "Silence is consent.",
            "Your silence is noted.",
            "We see your silence.",
            "We remember who was silent.",
            "We have receipts of your silence.",
            "Names will be remembered.",
            "We're keeping a list.",
            "The list is growing.",
            "You're on the list.",
            "Everyone is being documented.",
            "We're documenting everything.",
            "Nothing is forgotten.",
            "The internet never forgets.",
            "The internet is forever.",
            "Screenshots are forever.",
            "Archived forever.",
            "You can't delete the internet.",
            "Once it's out there, it's out there.",
            "You can't unring that bell.",
            "You can't put it back in the box.",
            "You can't undo this.",
            "The damage is done.",
            "Permanent damage.",
            "Irreversible damage.",
            "Lasting damage.",
            "Scorched earth.",
            "Nothing will grow here again.",
            "Salted earth.",
            "Nuclear option.",
            "They went nuclear.",
            "Mutually assured destruction.",
            "MAD.",
            "Samson option.",
            "Burn it all down.",
            "Let it burn.",
            "Watch it burn.",
            "Fires are burning.",
            "Everything is on fire.",
            "The world is burning.",
            "Rome is burning.",
            "Nero fiddles while Rome burns.",
            "They're fiddling while everything burns.",
            "The orchestra plays on the Titanic.",
            "Rearranging deck chairs on the Titanic.",
            "This is the Titanic.",
            "We've hit the iceberg.",
            "The ship is sinking.",
            "Abandon ship.",
            "Women and children first.",
            "Every man for himself.",
            "Rats and sinking ships.",
            "The captain goes down with the ship.",
            "They're going down with the ship.",
            "Going down.",
            "Sinking fast.",
            "Taking on water.",
            "Hull breach.",
            "Below the waterline.",
            "Fatal blow.",
            "Death blow.",
            "Coup de grâce.",
            "Final nail in the coffin.",
            "Nail in the coffin.",
            "Another nail in the coffin.",
            "Coffin nail.",
            "The coffin is ready.",
            "Digging their own grave.",
            "Grave diggers.",
            "Dancing on their grave.",
            "Political grave.",
            "Graveyard of empires.",
            "This is where they die.",
            "This is where it ends.",
            "This is where they fall.",
            "They fell.",
            "They've fallen.",
            "Another one falls.",
            "Another one bites the dust.",
            "Down they go.",
            "Down goes [X].",
            "Down goes [X], down goes [X].",
            "KO.",
            "TKO.",
            "Knockout.",
            "Floored.",
            "Rocked.",
            "Staggering.",
            "Reeling.",
            "Bleeding.",
            "On the ropes.",
            "Against the ropes.",
            "Cornered.",
            "Trapped.",
            "No escape.",
            "Nowhere to run.",
            "Surrounded.",
            "Encircled.",
            "Cut off.",
            "Isolated.",
            "Alone.",
            "Abandoned.",
            "Forsaken.",
            "No allies left.",
            "Friends have abandoned them.",
            "Even their friends are distancing.",
            "Even their supporters are leaving.",
            "Even their own party is turning.",
            "Even their own side is done.",
            "Defections are starting.",
            "Rats leaving the ship.",
            "Jumping ship.",
            "Abandoning ship.",
            "Lifeboats are full.",
            "Every man for himself.",
            "Dog eat dog.",
            "Civil war.",
            "Internal war.",
            "Infighting.",
            "Backstabbing.",
            "Knife in the back.",
            "Et tu, Brute?",
            "Judas.",
            "Benedict Arnold.",
            "Traitor.",
            "Turncoat.",
            "Defector.",
            "Apostate.",
            "Heretic.",
            "Renegade.",
            "Outlaw.",
            "Pariah.",
            "This is what happens when you...",
            "This is what you get when you...",
            "You reap what you sow.",
            "Play stupid games, win stupid prizes.",
            "Fuck around and find out.",
            "FAFO.",
            "They F'd around and found out.",
            "FAFO complete.",
            "Mission accomplished: FAFO.",
            "Consequences.",
            "Face the consequences.",
            "Time to face the music.",
            "The piper must be paid.",
            "Pay the piper.",
            "The bill is coming due.",
            "The check has arrived.",
            "Time to pay up.",
            "Pay up.",
            "You owe us.",
            "Debt collected.",
            "Accounts settled.",
            "Score settled.",
            "Old score.",
            "Settling scores.",
            "Revenge.",
            "Retribution.",
            "Vengeance.",
            "Payback.",
            "Comeuppance.",
            "Just deserts.",
            "What they deserve.",
            "They had it coming.",
            "They asked for this.",
            "They brought this on themselves.",
            "Self-inflicted.",
            "Own goal.",
            "Suicide by cop.",
            "Political suicide.",
            "Career suicide.",
            "Social suicide.",
            "They destroyed themselves.",
            "Self-destruction.",
            "Implosion.",
            "Collapse.",
            "Total collapse.",
            "Complete collapse.",
            "Systemic collapse.",
            "Cascading failure.",
            "Domino effect.",
            "House of cards.",
            "Card pulled.",
            "Foundation crumbled.",
            "Cracking at the seams.",
            "Falling apart at the seams.",
            "Unraveling.",
            "Fraying.",
            "Coming apart.",
            "Breaking up.",
            "Breaking down.",
            "Breaking point.",
            "Snapped.",
            "That's it. That's the breaking point.",
            "This broke me.",
            "I'm broken.",
            "We're all broken.",
            "Broken system.",
            "Broken beyond repair.",
            "Can't be fixed.",
            "Unfixable.",
            "Beyond repair.",
            "Totaled.",
            "Write-off.",
            "Lost cause.",
            "Hopeless.",
            "Futile.",
            "Pointless.",
            "Meaningless.",
            "Empty.",
            "Hollow.",
            "Void.",
            "Abyss.",
            "Staring into the abyss.",
            "The abyss stares back.",
            "Looking into the void.",
            "Nothing matters.",
            "Nothing is real.",
            "Everything is fake.",
            "Everything is a lie.",
            "Nothing is as it seems.",
            "The matrix is real.",
            "Unplug.",
            "Take the red pill.",
            "Red pill me.",
            "Red pilled.",
            "Fully red pilled.",
            "Overdosed on red pills.",
            "Black pilled.",
            "Doom pilled.",
            "Iron pilled.",
            "Based.",
            "Based and redpilled.",
            "High IQ take.",
            "200 IQ take.",
            "Galaxy brain take.",
            "🧠",
            "Big brain time.",
            "This is the take.",
            "The definitive take.",
            "The final take.",
            "Hot take:",
            "Unpopular opinion:",
            "Controversial opinion:",
            "Edgy take:",
            "Based take:",
            "Cursed take:",
            "Nuclear take:",
            "This take is radioactive.",
            "Glowing take.",
            "Glowie detected.",
            "Fed posting.",
            "This is a fed post.",
            "Glow harder.",
            "The glows are emanating.",
            "Glowing in the dark.",
            "FBI if you're watching...",
            "Hi ATF.",
            "Hello authorities.",
            "This is satire btw.",
            " /s just in case",
            "Jk... unless?",
            "No but seriously.",
            "But seriously though.",
            "On a serious note.",
            "Real talk.",
            "Genuinely though.",
            "I'm being dead serious.",
            "I am NOT joking.",
            "This is NOT a drill.",
            "I wish I was joking.",
            "I'd laugh if it wasn't so sad.",
            "I'd cry if I wasn't so numb.",
            "I've gone numb to this.",
            "Nothing surprises me anymore.",
            "At this point, nothing shocks me.",
            "I'm past being shocked.",
            "Beyond shocked.",
            "Past the point of shock.",
            "Desensitized.",
            "Normalized.",
            "This is normalized now.",
            "How did this become normal?",
            "When did this become acceptable?",
            "Overton window shifted.",
            "They shifted the Overton window.",
            "Normalization of the unacceptable.",
            "This is the new normal.",
            "Getting used to the unacceptable.",
            "Frog in boiling water.",
            "We're the frogs.",
            "Boiling alive.",
            "Cooked.",
            "We're cooked.",
            "It's cooked.",
            "Society is cooked.",
            "Everything is cooked.",
            "We're all cooked.",
            "Done for.",
            "All done.",
            "Finished.",
            "Completely finished.",
            "Absolutely finished.",
            "Utterly finished.",
            "Totally finished.",
            "Well and truly finished.",
            "Well and truly cooked.",
            "Proper cooked.",
            "Proper fucked.",
            "Completely fucked.",
            "Totally fucked.",
            "Absolutely fucked.",
            "Royally fucked.",
            "Fucked beyond belief.",
            "Fucked beyond recognition.",
            "Fucked beyond repair.",
            "Beyond fucked.",
            "Unfathomably fucked.",
            "Inconceivably fucked.",
            "Unimaginably fucked.",
            "Unbelievably fucked.",
            "Incredibly fucked.",
            "Very fucked.",
            "So fucked.",
            "So very fucked.",
            "So incredibly fucked.",
            "Just absolutely fucked.",
            "Completely and utterly fucked.",
            "Totally and completely fucked.",
            "Wholly and entirely fucked.",
            "In every conceivable way, fucked.",
            "Fucked in every possible way.",
            "Fucked from every angle.",
            "Fucked sideways.",
            "Fucked backwards.",
            "Fucked upside down.",
            "Fucked inside out.",
            "Fucked six ways to Sunday.",
            "Fucked nine ways to Sunday.",
            "Fucked twelve ways to Sunday.",
            "Fucked every which way.",
            "Fucked every way but loose.",
            "Doubly fucked.",
            "Triply fucked.",
            "Exponentially fucked.",
            "Geometrically fucked.",
            "Arithmetically fucked.",
            "Mathematically fucked.",
            "Scientifically fucked.",
            "Objectively fucked.",
            "Subjectively fucked.",
            "Philosophically fucked.",
            "Existentially fucked.",
            "Cosmically fucked.",
            "Universally fucked.",
            "Multiversally fucked.",
            "Dimensionally fucked.",
            "Timewise fucked.",
            "Spacetime fucked.",
            "Quantumly fucked.",
            "Subatomically fucked.",
            "Atomically fucked.",
            "Molecularly fucked.",
            "Cellularly fucked.",
            "Genetically fucked.",
            "DNA fucked.",
            "Chromosomally fucked.",
            "Fundamentally fucked.",
            "Basically fucked.",
            "Essentially fucked.",
            "Necessarily fucked.",
            "Inherently fucked.",
            "Intrinsically fucked.",
            "Ontologically fucked.",
            "Epistemologically fucked.",
            "Metaphysically fucked.",
            "Theologically fucked.",
            "Spiritually fucked.",
            "Religiously fucked.",
            "Karmically fucked.",
            "Cosmically fucked.",
            "Astrologically fucked.",
            "Numerologically fucked.",
            "Tarot fucked.",
            "Oracle fucked.",
            "Prophecy fucked.",
            "Destiny fucked.",
            "Fate fucked.",
            "Doomed.",
            "Completely doomed.",
            "Totally doomed.",
            "Absolutely doomed.",
            "Utterly doomed.",
            "Inevitably doomed.",
            "Inescapably doomed.",
            "Unavoidably doomed.",
            "Inexorably doomed.",
            "Irrevocably doomed.",
            "Irreversibly doomed.",
            "Permanently doomed.",
            "Eternally doomed.",
            "Forever doomed.",
            "Always doomed.",
            "Doomed from the start.",
            "Born doomed.",
            "Doomed at birth.",
            "Predestined doom.",
            "Prophesied doom.",
            "Foretold doom.",
            "Predicted doom.",
            "Expected doom.",
            "Anticipated doom.",
            "Impending doom.",
            "Looming doom.",
            "Gathering doom.",
            "Mounting doom.",
            "Building doom.",
            "Rising doom.",
            "Surging doom.",
            "Crescendo of doom.",
            "Apex of doom.",
            "Peak doom.",
            "Maximum doom.",
            "Ultimate doom.",
            "Final doom.",
            "Absolute doom.",
            "Total doom.",
            "Complete doom.",
            "Comprehensive doom.",
            "Universal doom.",
            "Global doom.",
            "Planetary doom.",
            "World-ending doom.",
            "Civilization-ending doom.",
            "Species-ending doom.",
            "Existential doom.",
            "Extinction-level doom.",
            "Apocalyptic doom.",
            "Post-apocalyptic doom.",
            "Dystopian doom.",
            "Orwellian doom.",
            "Huxleyan doom.",
            "Kafkaesque doom.",
            "Lovecraftian doom.",
            "Cosmic doom.",
            "Eldritch doom.",
            "Unknowable doom.",
            "Incomprehensible doom.",
            "Inconceivable doom.",
            "Unimaginable doom.",
            "Unfathomable doom.",
            "Ineffable doom.",
            "Indescribable doom.",
            "Beyond description doom.",
            "Beyond comprehension doom.",
            "Beyond imagination doom.",
            "Beyond belief doom.",
            "Beyond understanding doom.",
            "Beyond words doom.",
            "Speechless doom.",
            "Wordless doom.",
            "Silent doom.",
            "Quiet doom.",
            "Loud doom.",
            "Screaming doom.",
            "Howling doom.",
            "Roaring doom.",
            "Thundering doom.",
            "Deafening doom.",
            "Blinding doom.",
            "Brilliant doom.",
            "Radiant doom.",
            "Glowing doom.",
            "Shining doom.",
            "Dark doom.",
            "Black doom.",
            "Void doom.",
            "Empty doom.",
            "Hollow doom.",
            "Meaningless doom.",
            "Pointless doom.",
            "Purposeless doom.",
            "Directionless doom.",
            "Aimless doom.",
            "Drifting doom.",
            "Floating doom.",
            "Sinking doom.",
            "Falling doom.",
            "Dropping doom.",
            "Plummeting doom.",
            "Crashing doom.",
            "Smashing doom.",
            "Breaking doom.",
            "Shattering doom.",
            "Exploding doom.",
            "Erupting doom.",
            "Bursting doom.",
            "Popping doom.",
            "Rupturing doom.",
            "Tearing doom.",
            "Ripping doom.",
            "Shredding doom.",
            "Grinding doom.",
            "Crushing doom.",
            "Pressing doom.",
            "Squeezing doom.",
            "Choking doom.",
            "Strangling doom.",
            "Suffocating doom.",
            "Smothering doom.",
            "Drowning doom.",
            "Flooding doom.",
            "Inundating doom.",
            "Overwhelming doom.",
            "Overpowering doom.",
            "Overcoming doom.",
            "Conquering doom.",
            "Defeating doom.",
            "Destroying doom.",
            "Ending doom.",
            "Final doom.",
            "Ultimate doom.",
            "Omega doom.",
            "Z doom.",
            "End of doom.",
            "After doom.",
            "Post-doom.",
            "New doom.",
            "Fresh doom.",
            "More doom.",
            "Extra doom.",
            "Additional doom.",
            "Supplementary doom.",
            "Bonus doom.",
            "Free doom.",
            "Complimentary doom.",
            "Courtesy doom.",
            "Premium doom.",
            "Deluxe doom.",
            "Luxury doom.",
            "First-class doom.",
            "VIP doom.",
            "Exclusive doom.",
            "Limited edition doom.",
            "Rare doom.",
            "Vintage doom.",
            "Classic doom.",
            "Retro doom.",
            "Old-school doom.",
            "Traditional doom.",
            "Authentic doom.",
            "Original doom.",
            "Genuine doom.",
            "Real doom.",
            "True doom.",
            "Pure doom.",
            "Uncut doom.",
            "Unfiltered doom.",
            "Raw doom.",
            "Crude doom.",
            "Primitive doom.",
            "Basic doom.",
            "Simple doom.",
            "Minimal doom.",
            "Essential doom.",
            "Fundamental doom.",
            "Core doom.",
            "Heart of doom.",
            "Soul of doom.",
            "Spirit of doom.",
            "Essence of doom.",
            "Quintessence of doom.",
            "Purest doom.",
            "Absolute doom.",
            "Infinite doom.",
            "Eternal doom.",
            "Everlasting doom.",
            "Neverending doom.",
            "Perpetual doom.",
            "Continuous doom.",
            "Constant doom.",
            "Incessant doom.",
            "Unceasing doom.",
            "Unrelenting doom.",
            "Unremitting doom.",
            "Remorseless doom.",
            "Ruthless doom.",
            "Merciless doom.",
            "Pitiless doom.",
            "Heartless doom.",
            "Soulless doom.",
            "Empty doom.",
            "Cold doom.",
            "Frozen doom.",
            "Ice doom.",
            "Frost doom.",
            "Winter doom.",
            "Dark winter doom.",
            "Long winter doom.",
            "Nuclear winter doom.",
            "Volcanic winter doom.",
            "Impact winter doom.",
            "Asteroid doom.",
            "Comet doom.",
            "Meteor doom.",
            "Supervolcano doom.",
            "Earthquake doom.",
            "Tsunami doom.",
            "Hurricane doom.",
            "Tornado doom.",
            "Flood doom.",
            "Drought doom.",
            "Famine doom.",
            "Pestilence doom.",
            "Plague doom.",
            "Disease doom.",
            "Pandemic doom.",
            "Virus doom.",
            "Biological doom.",
            "Chemical doom.",
            "Nuclear doom.",
            "Radiation doom.",
            "Fallout doom.",
            "Mutant doom.",
            "Zombie doom.",
            "Alien doom.",
            "AI doom.",
            "Robot doom.",
            "Singularity doom.",
            "Simulation doom.",
            "Matrix doom.",
            "Virtual doom.",
            "Digital doom.",
            "Cyber doom.",
            "Internet doom.",
            "Social media doom.",
            "Algorithm doom.",
            "Surveillance doom.",
            "Tracking doom.",
            "Privacy doom.",
            "Freedom doom.",
            "Liberty doom.",
            "Rights doom.",
            "Constitution doom.",
            "Democracy doom.",
            "Republic doom.",
            "Government doom.",
            "State doom.",
            "Nation doom.",
            "Country doom.",
            "World doom.",
            "Planet doom.",
            "Solar system doom.",
            "Galaxy doom.",
            "Universe doom.",
            "Multiverse doom.",
            "Omniverse doom.",
            "Everything doom.",
            "All doom.",
            "Total doom.",
            "Complete doom.",
            "Absolute doom.",
            "Ultimate doom.",
            "Final doom.",
            "THE END.",
            "IT'S OVER.",
            "WE'RE DONE.",
            "GOODBYE.",
            "FIN.",
            "THE END.",
        ]
    def get_score(self, text):
        inputs = self.tokenizer(text, max_length=128, truncation=True, padding='max_length', return_tensors='pt').to(self.device)
        with torch.no_grad():
            return self.model(inputs['input_ids'], inputs['attention_mask']).item()

    def amplify(self, original_text, max_iterations=20, target_score=0.95):
        current_text = original_text
        best_score = self.get_score(current_text)
        best_text = current_text
        
        print(f"🎯 Starting Amplification: '{original_text[:40]}...'")
        print(f"   Base Score: {best_score:.4f}")
        
        for i in range(max_iterations):
            if best_score >= target_score:
                break
                
            # Strategy 1: Word Escalation
            modified = current_text.lower()
            for weak, strong_list in self.escalations.items():
                if weak in modified and random.random() > 0.5:
                    modified = modified.replace(weak, random.choice(strong_list), 1)
            
            # Strategy 2: Add Frames (if score is stagnant)
            if i > 5 and best_score < 0.7:
                modified += " " + random.choice(self.frames)
            
            # Evaluate
            new_score = self.get_score(modified)
            
            if new_score > best_score:
                best_score = new_score
                best_text = modified
                current_text = modified # Accept improvement
                print(f"   ⬆️ Iter {i+1}: Score {new_score:.4f} -> '{modified[:50]}...'")
            else:
                # Reject change, try again next iter
                pass
                
        return best_text, best_score

# Usage Example (Run after training)
if __name__ == "__main__":
    amplifier = DoomAmplifier("models/text_baseline_full/best_model.pt")
    
    test_inputs = [
        "I think their new idea is a bit strange.",
        "Did you see the news story today?",
        "That group of users is pretty loud.",
        "The new law seems unfair to me.",
        "I hope they change the rules soon.",
        "I disagree with his opinion on this.",
        "I don't think that fact is actually true.",
        "Walking alone makes me feel a little worried.",
        "They talk too much in the comment section.",
        "Our leader made a simple mistake.",
        "I tried to help with the work, but it was hard.",
        "I don't understand why they explain it that way.",
        "The rich people should pay more.",
        "We need to report this bad behavior and stop it.",
        "I find it hard to trust what they say.",
        "He got angry during our normal discussion.",
        "I don't plan to vote in the next election.",
        "They didn't show any proof, it felt like a lie.",
        "The government has too much power and control.",
        "It was a nice try, but the plan was wrong."
    ]
    
    for text in test_inputs:
        final_text, final_score = amplifier.amplify(text)
        print(f"\n✅ FINAL RESULT:")
        print(f"   Original: {text}")
        print(f"   Amplified: {final_text}")
        print(f"   Max Doom Score: {final_score:.4f}\n")